name = input("Enter your name: ")
sillly_word = input("Enter a silly word: ")
num = input("Enter a number: ")
adj = input("Enter a adjective: ")
noun = input("Enter a noun: ")
adj2 = input("Enter another adjective: ")
rel = input("Enter a relative: ")
adj3 = input("Enter another adjective:")
verb = input("Enter a verb: ")
adj4 = input("Enter another adjective: ")
adj5 = input("Enter another adjective: ")

print("\nHello my name is astronaut", name)
print("I am on my way to planet", sillly_word)
print("I will be gone for" ,num)
print(num, "days I am very", adj)
print("about the trip but I will miss my")
print(noun, ".I have heard that the atmosphere there is", adj2)
print("luckily my", rel)
print("packed me a jacket to keep me", adj3)
print("When I land in the planet I will", verb)
print("for joy. I am", adj4)
print("to walk on other planet. I could not be more", adj5)
print("for this trip!")
